# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jonathan Cockrem
title: Software Developer
email: joncockrem@gmail.com
website: https://github.com/JohnnyGitH

# Social links
twitter_username: jc_totalportal
github_username:  JohnnyGitH
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: hellokittee88
linkedin_username: jonathan cockrem
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jonathan and I'm a software developer. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>C#</mark> and <mark>Hurting myself playing sports</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside  software, some of my other interests and hobbies are:
   - Gardening
   - Renovating the house
   - Playing basketball or volleyball
   - Learning guitar

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
